import raw from "./catalog.generated.json";

/**
 * BLAUPUNKT CATALOGUE
 *
 * Generated by `npm run import:blaupunkt` from the Blaupunkt Brochure 2026
 * supplied by the customer. Unlike RECOIL there is no separate price list to
 * reconcile against — the brochure prints MRP next to every model, so it is
 * both the pricing and the specification authority.
 *
 * The brochure lays several models out per page with a single photograph, so
 * most records arrive priced and specified but without an image that can be
 * attributed to one model. Those are held in the verification queue rather than
 * published against someone else's photograph.
 */

export type BlaupunktImage = {
  file: string;
  width: number;
  height: number;
  /** The catalogue page the photograph was taken from. */
  source: string;
};

export type BlaupunktProduct = {
  model: string;
  variant: string | null;
  name: string;
  slug: string;
  brand: "BLAUPUNKT";
  category: string;
  subcategory: string;
  group: string;
  mrp: number;
  sellingPrice: number;
  discountPct: number;
  specs: string[];
  heading: string;
  page: number;
  image: BlaupunktImage | null;
  flags: string[];
  published: boolean;
  source: string;
};

export type BlaupunktSummary = {
  generatedAt: string;
  source: { doc: string; edition: string; supplied: string; pages: number };
  totals: { parsed: number; published: number; held: number; withImage: number; skippedRows: number };
  flagCounts: Record<string, number>;
  flagMeanings: Record<string, string>;
  skipped: { page: number; reason: string; line: string }[];
};

const data = raw as unknown as { summary: BlaupunktSummary; products: BlaupunktProduct[] };

export const ALL_PRODUCTS: BlaupunktProduct[] = data.products;
export const SUMMARY: BlaupunktSummary = data.summary;

/** Storefront-visible: a confident model name, a price, specs and its own photograph. */
export const PRODUCTS: BlaupunktProduct[] = ALL_PRODUCTS.filter((p) => p.published);

/** Priced and imported, but not safe to list until a human resolves the flag. */
export const VERIFICATION_QUEUE: BlaupunktProduct[] = ALL_PRODUCTS.filter((p) => !p.published);

export function getBySlug(slug: string): BlaupunktProduct | undefined {
  return ALL_PRODUCTS.find((p) => p.slug === slug);
}
